### ISSUE TITLE
Render no_avatar SVG at correct hidpi resolution

### ISSUE THREAD

**Issue by liamwhite** [deliciousblackink/Derpibooru#1]
Delicious pixellation?
![](https://i.imgur.com/XRSBLZp.png)

[Original SVG image](https://derpicdn.net/assets/no_avatar-1f16e058f8de3098c829dbfded69eb028fc02f52cccb886edc659e93011545fe.svg)

**Comment by deliciousblackink** [comment]
Hi! Quite so. The image used for "no-avatar" is not resized to fit
different screens, yuck! I'll fix it soon.
(I have to manually convert the no-avatar.svg into PNGs since Android
pre-Lollipop does not support SVG out-of-the-box)

Thanks for taking your time to take a look at the app, by the way!
