### ISSUE TITLE
Ceased to work, crash at startup

### ISSUE THREAD

**Issue by Atulin** [deliciousblackink/Derpibooru#25]
I'm using the latest apk on Samsung Galaxy Trend Plus.

I tried launching the app today, but after the standard "Yikes! Couldn't connect to server!" message, which is just a standard message I got used to getting every time, it just crashes. Restarting the phone and clearing the app data doesn't help.

**Comment by deliciousblackink** [comment]
Acknowledged. I can't promise an exact date I fix this, but I believe it will be less than a week from now.

**Comment by Atulin** [comment]
Thanks, it's the only app that works with Derpibooru, and one of maybe two general Booru apps that aren't abandonware. Good to see you still update and fix it.

**Comment by deliciousblackink** [comment]
Resolved. Get the APK [here](https://github.com/deliciousblackink/Derpibooru/releases/tag/v1.5.4) :)
