### ISSUE TITLE
No longer works startup crash

### ISSUE THREAD

**Issue by sSomename** [deliciousblackink/Derpibooru#26]
It now crashes on attempt to open

**Comment by azlux** [comment]
same here

**Comment by deliciousblackink** [comment]
Acknowledged, reason known, but may take a day or two because I'm busy with the site itself but I'll get there.

**Comment by deliciousblackink** [comment]
Available as an APK [here](https://github.com/deliciousblackink/Derpibooru/releases/tag/v1.5.5).
