### ISSUE TITLE
Hamburger Button should not have animation enabled with full height Navigation Drawer.

### ISSUE THREAD

**Issue by ghost** [deliciousblackink/Derpibooru#5]
I just wanted to let you know that you made an error in not manually disabling the animation for the hamburger button used for the Navigation Drawer. There is a bug in the design libraries which causes this animation to be enabled by default.

I will post two paragraphs from an article hosted on a third-party site in which Roman Nurik (A well-known Design Advocate that works for Google) explains that an animated hamburger button should not be used for a Navigation Drawer at all.

"One of the solutions Google came up with between pre-L and L designs was the spinning arrow animation. As Roman Nurik has explained, this animation doesn't actually belong in a navigation drawer interaction. It's a beautiful bit of interface chrome, but it's worth looking at why it doesn't belong.

The animation was created for instances where a hamburger button appeared consistently, but the user entered a secondary view on top of the first. For an example of this, see the yet unreleased Google Search update. The hamburger icon lives in the search bar, so when the user transitions to the bar with search suggestions, the icon transforms into an arrow."

Here is the link to the full article in which Roman Nurik (Design Advocate working for Google) explains that the spinning arrow should not be used for a navigation drawer at all: http://www.androidpolice.com/2014/10/30/google-turns-design-inconsistency-ten-latest-round-navigation-drawers/

Since this article was posted last year, the correct usage of the animated hamburger button, as defined by Roman Nurik, has been implemented in the Google Search and Google Play Store applications which you can take a look at.

I'm going to provide a link to another third-party site which explains why this hamburger button animation should be disabled and how to do it. Refer to the section titled "The Spin Bars". https://medium.com/@sotti/navigation-drawer-styling-according-material-design-5306190da08f

You can also refer to the official Gmail, Inbox by Gmail, Google Calendar, Google Docs, Google Drive, Google Hangouts, Google I/O 2015, Google Keep, Google Photos, Google Sheets, and Google Play Store applications for an example of the correct implementation.

**Comment by liamwhite** [comment]
holy tl;dr batman
