### ISSUE TITLE
Comments with bp/no_avatar authors do not show their avatar

### ISSUE THREAD

**Issue by liamwhite** [deliciousblackink/Derpibooru#7]
![](https://i.imgur.com/mX8luIz.jpg)

**Comment by deliciousblackink** [comment]
Do you use an emulator or an actual device? I experience the same issue while running an AVD, but I can't reproduce it on a real ICS device.

**Comment by deliciousblackink** [comment]
Related to #1 and its fix 3f15166843936a86e1bb45ac0627292fcba843f1: it looks like [`CircleImageView`](https://github.com/hdodenhof/CircleImageView) doesn't work with vector drawables after all.

**Comment by liamwhite** [comment]
I'm running this on my Nexus 5X.
